spring:
  thymeleaf:
    catch: false                   #缓存配置
    prefix: classpath:/static/     #视图返回路径
  http:
    multipart:
      maxFileSize: 5MB       #单个文件上传大小限制 5*1024=5120k
      # maxRequestSize: 50MB    #总文件的上传大小限制
      max-request-size: 5MB
  mvc:
    view:
      prefix: /               #默认前缀
      suffix: .html           #响应页面默认后缀
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/test"
    username: "root"
    password: ""

imagepath:
  path : "D:/test"                  #原图地址
  cpath : "D:/image"                #裁剪图地址
  tpath : "D:/thumb"                #缩略图地址



server:
  port: 8080                  #默认端口

myProps: #自定义的属性和值
  path: D:/test
